@echo off

echo Batch File to delete non-shipment files for OSS Scan
echo Last update 11-21-25

set /p result=Please Enter the local path to your SW or Repository Workspace : 

del "%result%\*.a" /s /f /q
del "%result%\*.ada" /s /f /q
del "%result%\*.asm" /s /f /q
del "%result%\*.asp" /s /f /q
del "%result%\*.aspx" /s /f /q
del "%result%\*.awk" /s /f /q
del "%result%\*.a2l" /s /f /q
del "%result%\*.a2l_tpl" /s /f /q
del "%result%\*.AB" /s /f /q
del "%result%\*.adx" /s /f /q
del "%result%\*.arxml_tpl" /s /f /q
del "%result%\*.arxmlWOCANFD" /s /f /q
del "%result%\*.aux" /s /f /q
del "%result%\*.apc" /s /f /q
del "%result%\*.aph" /s /f /q
del "%result%\*.acl" /s /f /q
del "%result%\*.BACKUP" /s /f /q
del "%result%\*.bin" /s /f /q
del "%result%\*.bak" /s /f /q
del "%result%\*.buildinfo" /s /f /q
del "%result%\*.BAMF" /s /f /q
del "%result%\*.bld" /s /f /q
del "%result%\*.BZ" /s /f /q
del "%result%\*.bas" /s /f /q
del "%result%\*.bms" /s /f /q
del "%result%\*.bcfg" /s /f /q
del "%result%\*.bmp" /s /f /q
del "%result%\*.bz2" /s /f /q
del "%result%\*.class" /s /f /q
del "%result%\*.cdep" /s /f /q
del "%result%\*.cbl" /s /f /q
del "%result%\*.c_old" /s /f /q
del "%result%\*.c_tpl" /s /f /q
del "%result%\*.can" /s /f /q
del "%result%\*.cbf" /s /f /q
del "%result%\*.cfg" /s /f /q
del "%result%\*.cfg_tpl" /s /f /q
del "%result%\*.chk" /s /f /q
del "%result%\*.cin" /s /f /q
del "%result%\*.clf" /s /f /q
del "%result%\*.cmm" /s /f /q
del "%result%\*.cnt" /s /f /q
del "%result%\*.chm" /s /f /q
del "%result%\*.config" /s /f /q
del "%result%\*.COPYarxml" /s /f /q
del "%result%\*.cproject" /s /f /q
del "%result%\*.css" /s /f /q
del "%result%\*.ct" /s /f /q
del "%result%\*.cc" /s /f /q
del "%result%\*.csv" /s /f /q
del "%result%\*.cfc" /s /f /q
del "%result%\*.cfm" /s /f /q
del "%result%\*.cgi" /s /f /q
del "%result%\*.cls" /s /f /q
del "%result%\*.cpp" /s /f /q
del "%result%\*.cpy" /s /f /q
del "%result%\*.cs" /s /f /q
del "%result%\*.csi" /s /f /q
del "%result%\*.crtrt" /s /f /q
del "%result%\*.cmd" /s /f /q
del "%result%\*.cxx" /s /f /q
del "%result%\*.doc" /s /f /q
del "%result%\*.docx" /s /f /q
del "%result%\*.dcdep" /s /f /q
del "%result%\*.dcm" /s /f /q
del "%result%\*.dbc" /s /f /q
del "%result%\*.dat" /s /f /q
del "%result%\*.ddf" /s /f /q
del "%result%\*.dpp" /s /f /q
del "%result%\*.doxyfile" /s /f /q
del "%result%\*.dhdep" /s /f /q
del "%result%\*.dxc" /s /f /q
del "%result%\*.def" /s /f /q
del "%result%\*.eed" /s /f /q
del "%result%\*.el" /s /f /q
del "%result%\*.ecore" /s /f /q
del "%result%\*.elf" /s /f /q
del "%result%\*.eps" /s /f /q
del "%result%\*.err" /s /f /q
del "%result%\*.emf" /s /f /q
del "%result%\*.erl" /s /f /q
del "%result%\*.eap" /s /f /q
del "%result%\*.envelope" /s /f /q
del "%result%\*.exp" /s /f /q
del "%result%\*.ext" /s /f /q
del "%result%\*.f" /s /f /q
del "%result%\*.fdt" /s /f /q
del "%result%\*.fdx" /s /f /q
del "%result%\*.fnm" /s /f /q
del "%result%\*.f77" /s /f /q
del "%result%\*.f90" /s /f /q
del "%result%\*.for" /s /f /q
del "%result%\*.git" /s /f /q
del "%result%\*.fpp" /s /f /q
del "%result%\*.frm" /s /f /q
del "%result%\*.g77" /s /f /q
del "%result%\*.g90" /s /f /q
del "%result%\*.hh" /s /f /q
del "%result%\*.ht" /s /f /q
del "%result%\*.hpp" /s /f /q
del "%result%\*.hrtrt" /s /f /q
del "%result%\*.hrl" /s /f /q
del "%result%\*.htm" /s /f /q
del "%result%\*.html" /s /f /q
del "%result%\*.h_tpl" /s /f /q
del "%result%\*.hdep" /s /f /q
del "%result%\*.hex" /s /f /q
del "%result%\*.het" /s /f /q
del "%result%\*.hxx" /s /f /q
del "%result%\*.idl" /s /f /q
del "%result%\*.iml" /s /f /q
del "%result%\*.ini" /s /f /q
del "%result%\*.ifl" /s /f /q
del "%result%\*.ilst" /s /f /q
del "%result%\*.inc" /s /f /q
del "%result%\*.ind" /s /f /q
del "%result%\*.js" /s /f /q
del "%result%\*.jsp" /s /f /q
del "%result%\*.jws" /s /f /q
del "%result%\*.liv" /s /f /q
del "%result%\*.lock" /s /f /q
del "%result%\*.lst" /s /f /q
del "%result%\*.log" /s /f /q
del "%result%\*.lcf" /s /f /q
del "%result%\*.lcf_tpl" /s /f /q
del "%result%\*.l" /s /f /q
del "%result%\*.lisp" /s /f /q
del "%result%\*.loadrule" /s /f /q
del "%result%\*.mak" /s /f /q
del "%result%\*.mk" /s /f /q
del "%result%\*.map" /s /f /q
del "%result%\*.pas" /s /f /q
del "%result%\*.php" /s /f /q
del "%result%\*.php3" /s /f /q
del "%result%\*.php4" /s /f /q
del "%result%\*.pl" /s /f /q
del "%result%\*.ppt" /s /f /q
del "%result%\*.pptx" /s /f /q
del "%result%\*.pm" /s /f /q
del "%result%\*.py" /s /f /q
del "%result%\*.R" /s /f /q
del "%result%\*.rb" /s /f /q
del "%result%\*.rc" /s /f /q
del "%result%\*.rexx" /s /f /q
del "%result%\*.s" /s /f /q
del "%result%\*.sh" /s /f /q
del "%result%\*.scm" /s /f /q
del "%result%\*.sqb" /s /f /q
del "%result%\*.sql" /s /f /q
del "%result%\*.tcl" /s /f /q
del "%result%\*.tk" /s /f /q
del "%result%\*.txt" /s /f /q
del "%result%\*.v" /s /f /q
del "%result%\*.vb" /s /f /q
del "%result%\*.vbs" /s /f /q
del "%result%\*.dll" /s /f /q
del "%result%\*.ear" /s /f /q
del "%result%\*.exe" /s /f /q
del "%result%\*.gif" /s /f /q
del "%result%\*.gz" /s /f /q
del "%result%\*.jar" /s /f /q
del "%result%\*.jpg" /s /f /q
del "%result%\*.lib" /s /f /q
del "%result%\*.o" /s /f /q
del "%result%\*.obj" /s /f /q
del "%result%\*.png" /s /f /q
del "%result%\*.sar" /s /f /q
del "%result%\*.so" /s /f /q
del "%result%\*.war" /s /f /q
del "%result%\*.850" /s /f /q
del "%result%\*.a2l" /s /f /q
del "%result%\*.access" /s /f /q
del "%result%\*.api_description" /s /f /q
del "%result%\*.arxml" /s /f /q
del "%result%\*.arxml_tpl" /s /f /q
del "%result%\*.asc" /s /f /q
del "%result%\*.adoc" /s /f /q
del "%result%\*.au3" /s /f /q
del "%result%\*.BAMF" /s /f /q
del "%result%\*.bamf_tpl" /s /f /q
del "%result%\*.bat" /s /f /q
del "%result%\*.bat_MDG1tpl" /s /f /q
del "%result%\*.bat_MPCtpl" /s /f /q
del "%result%\*.bcfg" /s /f /q
del "%result%\*.bcfg_tpl" /s /f /q
del "%result%\*.bfc" /s /f /q
del "%result%\*.bld" /s /f /q
del "%result%\*.blf" /s /f /q
del "%result%\*.bs" /s /f /q
del "%result%\*.bsh" /s /f /q
del "%result%\*.c_original" /s /f /q
del "%result%\*.c_tpl" /s /f /q
del "%result%\*.can" /s /f /q
del "%result%\*.cbf" /s /f /q
del "%result%\*.certs" /s /f /q
del "%result%\*.cfg" /s /f /q
del "%result%\*.cfx" /s /f /q
del "%result%\*.chk" /s /f /q
del "%result%\*.chm" /s /f /q
del "%result%\*.cin" /s /f /q
del "%result%\*.clf" /s /f /q
del "%result%\*.clf_tpl" /s /f /q
del "%result%\*.cm_tpl" /s /f /q
del "%result%\*.cmd" /s /f /q
del "%result%\*.cmd_tpl" /s /f /q
del "%result%\*.cmm" /s /f /q
del "%result%\*.cnp" /s /f /q
del "%result%\*.csv" /s /f /q
del "%result%\*.config" /s /f /q
del "%result%\*.cop" /s /f /q
del "%result%\*.cpc" /s /f /q
del "%result%\*.cpl" /s /f /q
del "%result%\*.crtrt" /s /f /q
del "%result%\*.cproject" /s /f /q
del "%result%\*.csi" /s /f /q
del "%result%\*.csi_notused" /s /f /q
del "%result%\*.csi_tpl" /s /f /q
del "%result%\*.csproj" /s /f /q
del "%result%\*.cmpx" /s /f /q
del "%result%\*.classpath" /s /f /q
del "%result%\*.cg_info" /s /f /q
del "%result%\*.cdd" /s /f /q
del "%result%\*.css" /s /f /q
del "%result%\*.cst" /s /f /q
del "%result%\*.ct" /s /f /q
del "%result%\*.ctg" /s /f /q
del "%result%\*.d" /s /f /q
del "%result%\*.dat" /s /f /q
del "%result%\*.data" /s /f /q
del "%result%\*.db" /s /f /q
del "%result%\*.dba" /s /f /q
del "%result%\*.dbc" /s /f /q
del "%result%\*.dcm" /s /f /q
del "%result%\*.dcusr" /s /f /q
del "%result%\*.der" /s /f /q
del "%result%\*.dia" /s /f /q
del "%result%\*.doxy" /s /f /q
del "%result%\*.Doxyfile" /s /f /q
del "%result%\*.dpa" /s /f /q
del "%result%\*.dbc" /s /f /q
del "%result%\*.dpp" /s /f /q
del "%result%\*.dtd" /s /f /q
del "%result%\*.dvf" /s /f /q
del "%result%\*.dbo" /s /f /q
del "%result%\*.dvgroovy" /s /f /q
del "%result%\*.dxc" /s /f /q
del "%result%\*.EAP" /s /f /q
del "%result%\*.eclipseproduct" /s /f /q
del "%result%\*.ecore" /s /f /q
del "%result%\*.eed" /s /f /q
del "%result%\*.egg" /s /f /q
del "%result%\*.env" /s /f /q
del "%result%\*.elf" /s /f /q
del "%result%\*.emf" /s /f /q
del "%result%\*.eot" /s /f /q
del "%result%\*.eps" /s /f /q
del "%result%\*.exp" /s /f /q
del "%result%\*.ext" /s /f /q
del "%result%\*.fcf" /s /f /q
del "%result%\*.ftl" /s /f /q
del "%result%\*.filters" /s /f /q
del "%result%\*.gradle" /s /f /q
del "%result%\*.graphml" /s /f /q
del "%result%\*.grd" /s /f /q
del "%result%\*.groovy" /s /f /q
del "%result%\*.gvl" /s /f /q
del "%result%\*.gxl" /s /f /q
del "%result%\*.gitignore" /s /f /q
del "%result%\*.h_" /s /f /q
del "%result%\*.hex" /s /f /q
del "%result%\*.-h" /s /f /q
del "%result%\*.ht" /s /f /q
del "%result%\*.iml" /s /f /q
del "%result%\*.inc" /s /f /q
del "%result%\*.iuml" /s /f /q
del "%result%\*.ir" /s /f /q
del "%result%\*.ipdb" /s /f /q
del "%result%\*.iobj" /s /f /q
del "%result%\*.inv" /s /f /q
del "%result%\*.ico" /s /f /q
del "%result%\*.includepath" /s /f /q
del "%result%\*.inf" /s /f /q
del "%result%\*.info" /s /f /q
del "%result%\*.ini" /s /f /q
del "%result%\*.ini_tpl" /s /f /q
del "%result%\*.java" /s /f /q
del "%result%\*.ja" /s /f /q
del "%result%\*.jazzignore" /s /f /q
del "%result%\*.jfc" /s /f /q
del "%result%\*.json" /s /f /q
del "%result%\*.javapath" /s /f /q
del "%result%\*.lcf" /s /f /q
del "%result%\*.ld" /s /f /q
del "%result%\*.ld_backup" /s /f /q
del "%result%\*.ld_tpl" /s /f /q
del "%result%\*.ldb" /s /f /q
del "%result%\*.ldf" /s /f /q
del "%result%\*.libraries" /s /f /q
del "%result%\*.lic" /s /f /q
del "%result%\*.lnk" /s /f /q
del "%result%\*.loadrule" /s /f /q
del "%result%\*.lst" /s /f /q
del "%result%\*.m" /s /f /q
del "%result%\*.maneuverpath" /s /f /q
del "%result%\*.manifest" /s /f /q
del "%result%\*.mappings" /s /f /q
del "%result%\*.mcs" /s /f /q
del "%result%\*.md" /s /f /q
del "%result%\*.mcs" /s /f /q
del "%result%\*.met" /s /f /q
del "%result%\*.metadata" /s /f /q
del "%result%\*.mexw32" /s /f /q
del "%result%\*.mexw64" /s /f /q
del "%result%\*.MF" /s /f /q
del "%result%\*.mic" /s /f /q
del "%result%\*.mdl" /s /f /q
del "%result%\*.mdl-tpl" /s /f /q
del "%result%\*.mk" /s /f /q
del "%result%\*.mmap" /s /f /q
del "%result%\*.msg" /s /f /q
del "%result%\*.mot" /s /f /q
del "%result%\*.mm" /s /f /q
del "%result%\*.md5" /s /f /q
del "%result%\*.mtd" /s /f /q
del "%result%\*.mwe" /s /f /q
del "%result%\*.map" /s /f /q
del "%result%\*.name" /s /f /q
del "%result%\*.nbp" /s /f /q
del "%result%\*.nfo" /s /f /q
del "%result%\*.odx" /s /f /q
del "%result%\*.out" /s /f /q
del "%result%\*.opt" /s /f /q
del "%result%\*.options" /s /f /q
del "%result%\*.orti" /s /f /q
del "%result%\*.p_a" /s /f /q
del "%result%\*.p_c" /s /f /q
del "%result%\*.p_s" /s /f /q
del "%result%\*.pdb" /s /f /q
del "%result%\*.pdm" /s /f /q
del "%result%\*.pdmdb" /s /f /q
del "%result%\*.pdmp" /s /f /q
del "%result%\*.pds" /s /f /q
del "%result%\*.pem" /s /f /q
del "%result%\*.per" /s /f /q
del "%result%\*.par" /s /f /q
del "%result%\*.pay" /s /f /q
del "%result%\*.pdm" /s /f /q
del "%result%\*.proc_tpl" /s /f /q
del "%result%\*.pya" /s /f /q
del "%result%\*.pyc" /s /f /q
del "%result%\*.pf" /s /f /q
del "%result%\*.plt" /s /f /q
del "%result%\*.pp" /s /f /q
del "%result%\*.pre" /s /f /q
del "%result%\*.prefs" /s /f /q
del "%result%\*.preinc" /s /f /q
del "%result%\*.prj" /s /f /q
del "%result%\*.ptu" /s /f /q
del "%result%\*.PROC" /s /f /q
del "%result%\*.proc_tpl" /s /f /q
del "%result%\*.project" /s /f /q
del "%result%\*.prt" /s /f /q
del "%result%\*.ps1" /s /f /q
del "%result%\*.ps1_tpl" /s /f /q
del "%result%\*.pxd" /s /f /q
del "%result%\*.pyc" /s /f /q
del "%result%\*.pyd" /s /f /q
del "%result%\*.puml" /s /f /q
del "%result%\*.pu" /s /f /q
del "%result%\*.policy" /s /f /q
del "%result%\*.plx" /s /f /q
del "%result%\*.plantuml" /s /f /q
del "%result%\*.pickle" /s /f /q
del "%result%\*.pfx" /s /f /q
del "%result%\*.rpyx" /s /f /q
del "%result%\*.regex" /s /f /q
del "%result%\*.rng" /s /f /q
del "%result%\*.rpj" /s /f /q
del "%result%\*.rptdesign" /s /f /q
del "%result%\*.RSA" /s /f /q
del "%result%\*.rt" /s /f /q
del "%result%\*.rtrt" /s /f /q
del "%result%\*.rtp" /s /f /q
del "%result%\*.rtaos" /s /f /q
del "%result%\*.rtf" /s /f /q
del "%result%\*.rtmgxml" /s /f /q
del "%result%\*.rubasapath" /s /f /q
del "%result%\*.rst" /s /f /q
del "%result%\*.rodata_chk" /s /f /q
del "%result%\*.rodata" /s /f /q
del "%result%\*.rfg" /s /f /q
del "%result%\*.sample" /s /f /q
del "%result%\*.security" /s /f /q
del "%result%\*.seq" /s /f /q
del "%result%\*.SF" /s /f /q
del "%result%\*.sfl" /s /f /q
del "%result%\*.si" /s /f /q
del "%result%\*.srec" /s /f /q
del "%result%\*.suo" /s /f /q
del "%result%\*.sfl" /s /f /q
del "%result%\*.signalmanipulationpath" /s /f /q
del "%result%\*.sln" /s /f /q
del "%result%\*.spa" /s /f /q
del "%result%\*.src" /s /f /q
del "%result%\*.set" /s /f /q
del "%result%\*.stcfg" /s /f /q
del "%result%\*.suo" /s /f /q
del "%result%\*.svg" /s /f /q
del "%result%\*.sys" /s /f /q
del "%result%\*.sym" /s /f /q
del "%result%\*.sim" /s /f /q
del "%result%\*.sig" /s /f /q
del "%result%\*.scss" /s /f /q
del "%result%\*.sbsx" /s /f /q
del "%result%\*.tb2" /s /f /q
del "%result%\*.tlog" /s /f /q
del "%result%\*.tpa" /s /f /q
del "%result%\*.tbz" /s /f /q
del "%result%\*.tfl" /s /f /q
del "%result%\*.tsv" /s /f /q
del "%result%\*.tex" /s /f /q
del "%result%\*.tdb" /s /f /q
del "%result%\*.tcm" /s /f /q
del "%result%\*.tbz2" /s /f /q
del "%result%\*.tar" /s /f /q
del "%result%\*.tgz" /s /f /q
del "%result%\*.tiff" /s /f /q
del "%result%\*.targets" /s /f /q
del "%result%\*.TDF" /s /f /q
del "%result%\*.tdpa" /s /f /q
del "%result%\*.template" /s /f /q
del "%result%\*.tmp" /s /f /q
del "%result%\*.ts2" /s /f /q
del "%result%\*.tsd" /s /f /q
del "%result%\*.tst" /s /f /q
del "%result%\*.tt" /s /f /q
del "%result%\*.ttf" /s /f /q
del "%result%\*.typed" /s /f /q
del "%result%\*.url" /s /f /q
del "%result%\*.user" /s /f /q
del "%result%\*.unused" /s /f /q
del "%result%\*.url" /s /f /q
del "%result%\*.vcproj" /s /f /q
del "%result%\*.via" /s /f /q
del "%result%\*.via_tpl" /s /f /q
del "%result%\*.vsd" /s /f /q
del "%result%\*.vsdx" /s /f /q
del "%result%\*.vpcfg" /s /f /q
del "%result%\*.vcxproj" /s /f /q
del "%result%\*.woff" /s /f /q
del "%result%\*.whl" /s /f /q
del "%result%\*.woff2" /s /f /q
del "%result%\*.xltx" /s /f /q
del "%result%\*.xla" /s /f /q
del "%result%\*.xml_tpl" /s /f /q
del "%result%\*.xsd" /s /f /q
del "%result%\*.xsl" /s /f /q
del "%result%\*.xslt" /s /f /q
del "%result%\*.xt" /s /f /q
del "%result%\*.xvp" /s /f /q
del "%result%\*.xmi" /s /f /q
del "%result%\*.xml" /s /f /q
del "%result%\*.xt" /s /f /q
del "%result%\*.xls" /s /f /q
del "%result%\*.xlsx" /s /f /q
del "%result%\*.xdm" /s /f /q
del "%result%\*.xlsm" /s /f /q
del "%result%\*.xpt" /s /f /q
del "%result%\*.yml" /s /f /q
del "%result%\*.yaml" /s /f /q
del "%result%\*.ZB" /s /f /q
del "%result%\*.zip" /s /f /q
del "%result%\*.ZY" /s /f /q
del "%result%\*.ZZ" /s /f /q
del "%result%\*.tpl" /s /f /q
del "%result%\*.sim_src" /s /f /q
del "%result%\*.pdf" /s /f /q
del "%result%\*.h_tpl" /s /f /q
del "%result%\*.oaw" /s /f /q
del "%result%\*.properties" /s /f /q
del "%result%\*.tfl" /s /f /q
del "%result%\*._arxml" /s /f /q
del "%result%\*._c" /s /f /q
del "%result%\*._h" /s /f /q
del "%result%\*._old_arxml" /s /f /q
del "%result%\*.800" /s /f /q
del "%result%\*.7z" /s /f /q
del "%result%\*.1" /s /f /q

echo Done!